### ISSUE TITLE
context is a Hash instead of GraphQL::Query::Context, causing runtime errors

### ISSUE THREAD

**Issue by kurtome** [DmitryTsepelev/graphql-ruby-fragment_cache#46]
Hello,

I'm running into the exact same error that @CestarBe had in #26, namely that when the `context` object is being referenced by this library, it is just a `Hash` and not a `GraphQL::Query::Context`, therefore it does not have a method called `namespace`.

```
#<NoMethodError: undefined method `namespace' for #<Hash:0x00007f2bc3d9f8c8>>
```

I attempted to debug this by printing the class of `context` inside my `QueryType` object and it says that even there the `context` is just a `Hash`.

My query object looks something like this:

```ruby
class QueryType < Types::BaseObject
  field get_post, Post
  
  def post
    print(context.class) # <--- THIS IS A HASH
    PostResolver.new.call(object, args, context)
  end
end
```

Anyone have any ideas how this could be happening? My `GraphqlController` and `Schema` setups look just like the examples in the documentation.

**Comment by DmitryTsepelev** [comment]
Hi @kurtome, what version of `graphql-ruby` you have in your app? Is there a chance that you override a `context` method somewhere?

**Comment by kurtome** [comment]
@DmitryTsepelev It turns out my Pundit integration with GraphQL was misconfigured (some how the `Field` class for pundit was included on my base object). So that fixed the initial problem. Then I ran into #47. 

And now, I'm running into a new error with Pundit:
```
No policy found for:\n\n- Type: Post\n- Runtime value: #<GraphQL::Execution::Interpreter::RawValue:0x00007f9390c66670 @object=[{...},{...}...] ... >`\
```

I'm considering removing Pundit completely at this point to get around this :)

**Comment by DmitryTsepelev** [comment]
`RawValue` is way to tell interpreter that we have a value that is _already resolved_, so no further processing is required. Sounds like you cache a data that depends on the user and his permissions; in this case I'd rather not cache user–dependent data or patch Pundit somehow to let it know how to work with raw values (it holds the same data as a usual resolved object)

**Comment by kurtome** [comment]
That's what I was assuming, really good to know about `RawValue` in case I want to use it for other kinds of caching within GraphQL. I'm going to remove Pundit since it adds more complexity than is worth it.

Thanks for the help!

**Comment by DmitryTsepelev** [comment]
Check out https://github.com/palkan/action_policy-graphql, it might be a better fit 😉
