### ISSUE TITLE
Way to conditionally use fragment cache?

### ISSUE THREAD

**Issue by tjk** [DmitryTsepelev/graphql-ruby-fragment_cache#55]
Basically topic, but would like a way to only go through the cache under certain conditions (couldn't tell from code or docs if already supported). For example, if a particular query will explode the cardinality but I want the base case to be cached. Contrived example:

```ruby
field :search_movies, [MovieResultType], null: false do
  argument :query, String, required: false
end
def search_movies(query: nil)
  cache_fragment(disabled: !query.blank?) do
    Movie.do_expensive_search(query) # and expensive resolving
  end
end
```

**Comment by DmitryTsepelev** [comment]
Hi @tjk! Currently it's not possible via API, but we could to do a similar thing with plain Ruby:

```ruby
field :search_movies, [MovieResultType], null: false do
  argument :query, String, required: false
end

def search_movies(query: nil)
  if query.blank?
    cache_fragment(disabled: !query.blank?) do
      Movie.do_expensive_search(query) # and expensive resolving
    end
  else
    Movie.do_expensive_search(query) # and expensive resolving
  end
end
```

**Comment by tjk** [comment]
Yea considered this, just thought it was a little gross -- but I'll go with it for now! Thanks.

Would love to help with a patch if it's something you want added but I figure it's probably trivial enough that you communicating the API you'd like would take more effort than just doing it yourself... but let me know! :)

**Comment by DmitryTsepelev** [comment]
Yeah, I'm definitely open to PRs!

**Comment by tjk** [comment]
Pushed my first pass attempt here: https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/pull/56
