### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by mengqing** [DmitryTsepelev/graphql-ruby-fragment_cache#75]
I understand that you can setup namespace by either

1. ```GraphQL::FragmentCache.namespace = "my-prefix"```
2. ```GraphQL::FragmentCache.configure { |config| config.namespace = "my-prefix" }```

It isn't clear to me whether I can set namespace under `config.default_options`, eg

```
GraphQL::FragmentCache.configure do |config|
  config.default_options = {
    namespace: "my-prefix"
  }
end
```

However when I did the above, I got unexpected behaviour where the cache store tries to read the cache key without namespace but write with the namespace as part of the cache key.

Frankly I would expect namespace to be configured as part of the cache store options in which case each individual cache store would handle the namespace

**Comment by DmitryTsepelev** [comment]
Closing this for now, feel free to reopen 🙂
