### ISSUE TITLE
How do I expire a cached collection when a sub model changes?

### ISSUE THREAD

**Issue by macdonaldr93** [DmitryTsepelev/graphql-ruby-fragment_cache#78]
Hey there,

Love this gem. The examples show how to set cache keys for a single record. How do I expire cache keys for collections?

For example,

```ruby
class Post < ApplicationRecord
  has_many :comments
end

class Comment < ApplicationRecord
  belongs_to :post
end

# somewhere in the GraphQL schema
field :posts, [PostType], null: false, cache_fragment: { context_key: [:current_user] }
```

I'm not sure how to expire the cached "posts" field.

I tried using "touch". 

```ruby
class Comment < ApplicationRecord
  belongs_to :post, touch: true
end
```

But it's not expiring the posts field.

**Comment by macdonaldr93** [comment]
My next attempt is going to be

```ruby
class Post < ApplicationRecord
  has_many :comments
  
  def graphql_cache_key
    cache_key_with_version
  end
end

class Comment < ApplicationRecord
  belongs_to :post, touch: true
end
```

**Comment by DmitryTsepelev** [comment]
Hi @macdonaldr93! I feel like you could use the _last comment id_ as a part of the cache key: in this case we still do an extra query to fetch the latest comment but do not read the whole collection.

> I tried using "touch"...But it's not expiring the posts field.

I guess you need to explicitly include `updated_at` to the cache key to make it work

**Comment by macdonaldr93** [comment]
That's a good idea! Thanks for the suggestion. I ended up doing a touch on the parent model and then using cache_with_version. The reason this worked is that I was including the parent model in the context of the resolver. I'll explain with a more accurate example.

Given the following:

```ruby
class User < ApplicationRecord
end

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

class Comment < ApplicationRecord
  belongs_to :post
end

# somewhere in the GraphQL schema
field :posts, [PostType], null: false, cache_fragment: { context_key: [:current_user] }
```

I didn't want to do an additional query to build the cache key. I ended up using `touch` on the current user.

```ruby
class User < ApplicationRecord
  def graphql_cache_key
    cache_key_with_version
  end
end

class Post < ApplicationRecord
  belongs_to :user, touch: true
  has_many :comments
end

class Comment < ApplicationRecord
  belongs_to :post, touch: true
end
```

This works great! Thanks for replying and maintaining this gem :D
