### ISSUE TITLE
Specs fail when testing cached fields

### ISSUE THREAD

**Issue by jeromedalbert** [DmitryTsepelev/graphql-ruby-fragment_cache#87]
I have a spec that unit tests a cached graphql field using a custom spec helper.

The class to test and the spec look something like this:

```ruby
# app/graphql/types/objects/post_type.rb
module Types
  module Objects
    class PostType < Base
      field :comments, Types::Objects::CommentType.connection_type, cache_fragment: true

      def comments
        # ...
      end
    end
  end
end

# spec/graphql/types/objects/post_type_spec.rb
module Types
  module Objects
    describe PostType do
      subject(:post) { create(:post) }

      describe '#comments' do
        before { create_list(:comment, 2, post: post) }

        it { expect(resolve(post, :comments).count).to eq 2 }
      end
    end
  end
end
```

And the file that provides the `resolve` helper method looks a bit like this:

```ruby
# spec/support/graphql/helpers.rb
module GraphQL
  module Helpers
    def resolve(object, field, args = {})
      query = GraphQL::Query.new(MyAppSchema, context: context)
      field = subject.fields[field.to_s.camelize(:lower)]
      type_instance = described_class.authorized_new(object, query.context)
      args.transform_keys! { |arg| arg.to_s.underscore.to_sym }

      resolved = field.resolve(type_instance, args, query.context)

      if resolved.is_a?(GraphQL::Pagination::Connection)
        resolved.nodes
      else
        resolved
      end
    end
  end
end
```

But when I run the spec I get the following error:

```console
 NoMethodError:
   undefined method `count' for #<GraphQL::Execution::Lazy:0x00007f7e583a5010>
 # ./spec/graphql/types/objects/post_type_spec.rb:1287:in `block (4 levels) in <module:Objects>'
```

The problem is that in my graphql helper, `resolved` is a `GraphQL::Execution::Lazy` object, and this object behaves differently than a more traditional `GraphQL::Pagination::Connection` object.

I am not familiar with `graphql-ruby`'s internals. I tried `resolved.value` but I get another error

```console
NoMethodError: undefined method `operation_type' for nil:NilClass
from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.6/lib/graphql/query.rb:167:in `lookahead'
```

Maybe I somehow need to provide `operation_type` in my helper, although I don't know what value I could provide and where. Or maybe I am on the wrong path.

Any idea what I would need to fix this? Like how to get the nodes from a `GraphQL::Execution::Lazy`?

In the meantime I have disabled caching for the test environment with the [following monkey patch](https://gist.github.com/jeromedalbert/68e58ce62563b3950bf5d715ca45fced). If noone has any idea, maybe converting my monkey patch into a PR could be an acceptable workaround.

**Comment by DmitryTsepelev** [comment]
Hey @jeromedalbert, could you please try to use [then](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/lazy.rb#L55)? Something like `resolved.then { |value| ... }`

**Comment by jeromedalbert** [comment]
No luck with that, it returns a `GraphQL::Execution::Lazy` too

**Comment by jeromedalbert** [comment]
I think the root cause of the problem is that my `resolve` helper code does not define any query in `GraphQL::Query.new`. That is why I am getting errors about a nil `operation_type`, since no operation (query or mutation or subscription) is defined.

Just for the heck of it I tried passing a placeholder query  `GraphQL::Query.new(MyAppSchema, 'query { posts { title }  }', context: context)` and then do `resolved.value`, but that gives me

```console
NoMethodError: undefined method `map' for nil:NilClass
from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-fragment_cache-1.13.1/lib/graphql/fragment_cache/cache_key_builder.rb:177:in `bl
ock in path_cache_key'
```

because the `CacheKeyBuilder` `path` is nil. It makes sense since I am trying to shoehorn a query that is not being executed the normal way.

`graphql-ruby-fragment_cache` needs a path to compute its cache key, but my `resolve` helper code never provides one. As is, the helper code is incompatible with the gem. It might be possible to make it work by making the helper generate a query from the field name, and there would still be this nil `path` issue to figure out, but I think it is overkill, the simplest solution is probably to disable cache processing.
