### ISSUE TITLE
Make the cache key human-readable

### ISSUE THREAD

**Issue by jeromedalbert** [DmitryTsepelev/graphql-ruby-fragment_cache#88]
I have the following quick and dirty monkey patch:

```ruby
# Monkey patch to make the cache key more human-readable for easier debugging
module GraphQL
  module FragmentCache
    class CacheKeyBuilder
      module MonkeyPatch
        def implicit_cache_key
          full_cache_key = query_cache_key
          cache_key_first_part = full_cache_key.split('(').first.split('[').first.tr('/', '-')
          hex_cache_key = Digest::SHA1.hexdigest(full_cache_key)

          "#{cache_key_first_part}/#{hex_cache_key}"
        end

        def object_cache_key
          super&.tr('/', '-')
        end
      end
      prepend MonkeyPatch
    end
  end
end
```

This makes cache keys look like this:

```
[41] pry(main)> $redis.keys('graphql*').sort
[
    [ 0] "graphql/post/766b6ccc10ab9495379351ee8beafea5c6007503/1595-mycorp",
    [ 1] "graphql/currentTenant-activities/8fb06e96554aadb59acc95055d94ac32e35ad383/1595-mycorp",
    [ 2] "graphql/currentTenant-posts/f328972b1d41071057c1e9b2ba2942376ead0def/posts-query-5f6b140cd0b110df8830cb806289afae-6-20220927164337385299-mycorp",
    [ 3] "graphql/currentTenant-orgs/8cd8ca77d3d80ce63a3c71f3458e13f871976742/orgs-query-a1cd705421842de6905cfb2f6c372fc8-1-20220908170650370442-mycorp",
    [ 4] "graphql/currentTenant-orgs/9d43405f9a04e5a7007c7a5b23e9a83025195513/orgs-query-a1cd705421842de6905cfb2f6c372fc8-1-20220908170650370442-mycorp",
    [ 5] "graphql/currentUser-companies-0-plans/636959b06ed3087a042294887cf024825324b17d/companies-28712-20221017002729396154-mycorp",
    [ 6] "graphql/currentUser-companies/3ce35c987a1634135bfdde439535f8d0d80c70ab/users-234196-20221017141421202813-mycorp",
    [ 7] "graphql/tool/136783447b0def9ee3eeffdee6e7d0724b25729d",
    [ 8] "graphql/tool/18ab5818aea282fc778f11f263862d7420491eab/tools-989-20221018005011056666-mycorp",
    [ 9] "graphql/tool/476a0e82181713884b6fc38efd8668cb55b35e16/companies-1281-20221018005011252828-mycorp",
    [10] "graphql/tool/59965cf1a9b31ce7dae6722c5a786a66658c865e/tools-989-20221018005011056666-mycorp"
]
```

What is nice is that I now get a pretty good idea of what the key is about: the query fingerprint is still there in the middle, but it is prefixed with the query path in plain text, and suffixed with the object cache key in plain text. 

This has proved very valuable:
- when debugging what my keys look like in development, to make sure I am caching with the right object key, saving a lot of potential headaches and bug investigations downstream
- when searching for keys in general (`$redis.keys('*activities*')`) or for a particular customer (`$redis.keys('*activities*mycorp')`)
- when surgically deleting bad keys for a given query or customer in production (`Rails.cache.delete_matched('*posts*')`) without having to use the nuclear `Rails.cache.clear` option

On the flip side the keys are longer, but in practice it hasn't been a problem in my app. I should also mention that I am using redis as my cache store, and since the max key size is 512 MB, I probably won't ever have the issue of keys being too long.

I feel like an option to make keys more human-readable (or maybe even by default) would be helpful. But maybe my needs are too specific.

Do you this is somewhat useful? If so we could make a PR.

**Comment by DmitryTsepelev** [comment]
Hi! Yeah, this sounds reasonable, would be really nice to have it in the gem 🙂

**Comment by jeromedalbert** [comment]
@DmitryTsepelev Do you want this feature as a default or an option?

**Comment by DmitryTsepelev** [comment]
@jeromedalbert let's make it new default 🙂
