### ISSUE TITLE
Upgrade to 1.18.0 version error

### ISSUE THREAD

**Issue by luciiii6** [DmitryTsepelev/graphql-ruby-fragment_cache#95]
Hi, I am trying to upgrade the gem to the latest version (1.8.0) and ran into some problems. We are using ddtracerb and it is expecting to receive a hash instead of an array to write_multi function:

This is the error rescued and then raised by your code:

```
GraphQL::FragmentCache::WriteMultiError:
  undefined method 'keys' for ["graphql/ids/368d52c087dfcf3113a577315c45e3036b316410", {"data": "test"}]:Array

                    keys: hash.keys,
                              ^^^^^
/home/circleci/.rubygems/gems/graphql-fragment_cache-1.18.0/lib/graphql/fragment_cache/cacher.rb:52:in `rescue in block in batched_persist'
```

And this is the original error:

```
--- Caused by: ---
NoMethodError:
  undefined method `keys' for ["graphql/ids/368d52c087dfcf3113a577315c45e3036b316410", {"data":"test"}]:Array
  
                    keys: hash.keys,
                              ^^^^^
  /home/circleci/.rubygems/gems/ddtrace-1.8.0/lib/datadog/tracing/contrib/active_support/cache/instrumentation.rb:234:in `write_multi'

```

This is the code where it comes from: [ddtrace code](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/active_support/cache/instrumentation.rb#L234)

Also the ruby version used is: 3.1.3

**Comment by DmitryTsepelev** [comment]
Hey @luciiii6! Looks like I made a stupid mistake and passed hash as `*hash`, here's a [fix](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/pull/96) and I rolled out `1.18.1`, please let me know if it helps 🙂

**Comment by luciiii6** [comment]
Works like a charm, thank you for the fix! :smiley:
