### ISSUE TITLE
Cache connection type using multi

### ISSUE THREAD

**Issue by andrezimpel** [DmitryTsepelev/graphql-ruby-fragment_cache#97]
First of all, thank you for your great gem!

I am running into the following issue tho: I have all_pages field:
`field :all_pages, PageType.connection_type, null: true`

When I resolve and cache it using the gem all the pages get cached - which makes sense of course.

```ruby
def all_pages
  cache_fragment {
    chain = Page
    chain = scope_status(chain, context[:stage])
    chain = lookahead_for_collection(chain, lookahead)
    chain = search_records(chain, search)
    chain = order_records(chain, order)
    chain.all
  }
end
```

I am using the api in a Gatsby website. So whenever there is an update in my rails app a webhook gets posted to Gatsby Cloud to rebuild the site. This rebuild will fetch all pages with all available fields which is very heavy. Also because they are a lot.

Is there an option to cache all pages but only invalidate a single one (similar to rails.cache.fetch_multi) so that all pages that did not change get fetched from the cache except the one that changed? This would speed up my app significantly.

Thank you! 💜

**Comment by DmitryTsepelev** [comment]
Hey @andrezimpel, thank you for the warm words 🙂

I guess it's not currently possible, because in our case cache uses a query with variables as a key and the whole JSON response as a value. I guess it's technically possible to cache individual pages and then make response from them, but that sounds a bit fragile.

**Comment by andrezimpel** [comment]
Dear @DmitryTsepelev makes sense! I updated my app to use your gem but also batch-loader. It speeds up everything.

One question I was wondering about is how to invalidate a fragment?

Let's say this is my cache_key: `page/1674714708/main/108`

How can I invalidate that key?

**Comment by DmitryTsepelev** [comment]
Hey @andrezimpel! What storage are you using? If it's memory — you can only restart the server, if Redis — go to the console and drop it from there 🙂
